FROM ubuntu:17.04

RUN apt-get -y update && apt-get -y upgrade && apt-get -y install \
    apt-utils \
    apache2 \
    supervisor \
    libapache2-mod-php7.0 \
    php7.0-mbstring \
    php-xdebug \
    php7.0-dom \
    php7.0-zip \
    php7.0-pdo \
    php7.0-mysql \
    bzip2 \
    libfontconfig \
    mysql-client \
    curl \
    wget \
    rsync \
    nodejs \
    npm \
    default-jre \
    default-jdk \
    maven \
    mc
